name: "Publish DocC to Gitub Pages"
description: "A composite action that creates a DocC archive and publishes it to Github Pages"
author: "acarlson"
inputs:
  branch:
    description: "branch to build documentation from"
    default: ${{ github.event.inputs.branch }}
    required: true
  scheme:
    description: "xcode scheme to publish"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout branch
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.branch }}

    - name: Create Archive
      shell: sh
      run: |
        BUILD_DIR=$RUNNER_TEMP/build

        xcodebuild docbuild \
          -scheme $INPUT_SCHEME \
          -derivedDataPath $BUILD_DIR \
          -allowProvisioningUpdates
      env:
        INPUT_SCHEME: ${{ inputs.scheme }}

    - name: Tansform for static hosting
      shell: sh
      run: |
        BUILD_DIR=$RUNNER_TEMP/build
        ARCHIVE=$(find $BUILD_DIR -type d -name '*.doccarchive')

        # Transform for static hosting
        cmd() {
          echo "$ARCHIVE" | awk -F'/' '{print tolower($NF)}' | awk -F'.' '{print $(1)}'
        }
        ARCHIVE_NAME="$(cmd)"

        mkdir $RUNNER_TEMP/docs

        DOCC_OUTPUT_PATH=$RUNNER_TEMP/docs/$ARCHIVE_NAME
        INDEX_FILENAME=$RUNNER_TEMP/docs/index.html

         echo "DOCS_PATH=$RUNNER_TEMP/docs" >> $GITHUB_ENV

        $(xcrun --find docc) process-archive transform-for-static-hosting "$ARCHIVE" \
          --hosting-base-path $INPUT_REPO_NAME/$ARCHIVE_NAME \
          --output-path $DOCC_OUTPUT_PATH

        # Make index.html
        DOCS_URL=./$ARCHIVE_NAME/documentation/$ARCHIVE_NAME/

        cat > $INDEX_FILENAME << ENDOFFILE
        <!DOCTYPE html>
        <meta charset="utf-8">
        <meta http-equiv="refresh" content="1; url=$DOCS_URL">
        <script>
          window.location.href = "$DOCS_URL"
        </script>
        <title>Redirecting...</title>
        If you are not redirected automatically, follow
        <a href="$DOCS_URL">
          this link
        </a>.

      env:
        INPUT_SCHEME: ${{ inputs.scheme }}
        INPUT_REPO_NAME: ${{ github.event.repository.name }}

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ${{ env.DOCS_PATH }}

    - name: Publish to Pages
      uses: actions/deploy-pages@v2
